import Head from 'next/head'
import { Inter } from '@next/font/google'
import Layout from '@/components/layout'

import BannerLink from '@/components/banner'
import { PBI } from '@/content/iframes';
import { IframeProps } from '@/@Types/iframes';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const anchorCustommer = PBI.map(({ name }: IframeProps) => name);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      
      <Layout className={`w-full min-h-screen h-auto flex flex-col items-center bg-blue-100 ${inter.className}`}>
        <div className={"h-auto w-full py-5 sm:h-full flex items-center sm:justify-center flex-wrap flex-col gap-2.5 relative"}>
          <BannerLink
            content={anchorCustommer[0]}
            src={"/image/3.png"}
            classNameLink={"w-11/12 h-96"}
          />
          <BannerLink
            content={anchorCustommer[1]}
            src={"/image/4.png"}
            classNameLink={"w-11/12 h-96"}
          />
        </div>
      </Layout>
    </>
  )
}