import Head from 'next/head'
import { Inter } from '@next/font/google'
import Layout from '@/components/layout'

import BannerLink from '@/components/banner'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      
      <Layout className={`w-full min-h-screen h-auto flex flex-col items-center gap-2 bg-blue-100 ${inter.className}`}>
        <h5
          className={"text-black text-2xl h-10 my-2.5 text-center"}
        >
          Relatório Agentes Locais de Inovação
        </h5>

        <div className={"h-auto w-full pb-5 sm:p-0 sm:h-full flex items-center sm:justify-center flex-wrap flex-col sm:flex-nowrap sm:flex-row gap-2.5 relative"}>
          <BannerLink
            href="https://sites.google.com/sebraealimg.com/ali-transformacao-digital/p%C3%A1gina-inicial"
            src={"/image/ali-td.png"}
            classNameLink={"w-11/12 sm:w-6/12 h-96"}
          />
          <BannerLink
            href="https://sites.google.com/view/alibrasilmaismg/p%C3%A1gina-inicial"
            src={"/image/ali-prod.jpg"}
            classNameLink={"w-11/12 sm:w-6/12 h-96"}
            classNameImg={"object-left"}
          />
        </div>
      </Layout>
    </>
  )
}